title: pd
baseurl: '/'
permalink: "/:path/"
url: "pnkdrmmr.github.io" # your site's origin, e.g. https://forestry.io
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
# tag_page_layout: tag_page
# tag_page_dir: tag
jekyll-archives:
  enabled: all
  layout: "archive"
sass:
    sass_dir: css
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
