---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - custom-page
  - landing-page
- type: document
  path: _data/hard-menus.yml
  label: Menu
- type: document
  path: _data/information.yml
  label: Contact Information
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
